Add docs for Session only cookies
gofiber/docs pull request #240
Opened 2022-02-07 12:31 UTC by abhi12299

Pending task for [this PR](https://github.com/gofiber/fiber/pull/1752)

2022-02-07 12:38 UTC, ReneWerner87 requested changes
please refresh the csrf documentation

2022-02-07 12:38 UTC, ReneWerner87 commented on original/context.md
> +	SessionOnly bool
please don´t change this file, its for the old version

2022-02-08 02:29 UTC, abhi12299 commented
@ReneWerner87 please review the changes

2022-02-08 07:25 UTC, ReneWerner87 commented
@abhi12299 looks good so far, can you correct the indentations

2022-02-08 07:51 UTC, abhi12299 commented
@ReneWerner87 done.

2022-02-08 08:08 UTC, ReneWerner87 approved these changes

2022-02-14 14:44 UTC, merged